package ni.org.ics.estudios.appmovil.helpers.covid19;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.estudios.appmovil.domain.covid19.CuestionarioCovid19;
import ni.org.ics.estudios.appmovil.utils.Covid19DBConstants;
import ni.org.ics.estudios.appmovil.utils.MainDBConstants;

import java.util.Date;

public class CuestionarioCovid19Helper {

    public static ContentValues crearCuestionarioCovid19ContentValues(CuestionarioCovid19 cuestionario){
        ContentValues cv = new ContentValues();
        cv.put(Covid19DBConstants.codigo, cuestionario.getCodigo());
        if (cuestionario.getParticipante()!=null) cv.put(Covid19DBConstants.participante, cuestionario.getParticipante().getCodigo());
        /*
        cv.put(Covid19DBConstants.feb20Febricula, cuestionario.getFeb20Febricula());
        cv.put(Covid19DBConstants.feb20Fiebre, cuestionario.getFeb20Fiebre());
        cv.put(Covid19DBConstants.feb20Escalofrio, cuestionario.getFeb20Escalofrio());
        cv.put(Covid19DBConstants.feb20TemblorEscalofrio, cuestionario.getFeb20TemblorEscalofrio());
        cv.put(Covid19DBConstants.feb20DolorMuscular, cuestionario.getFeb20DolorMuscular());
        cv.put(Covid19DBConstants.feb20DolorArticular, cuestionario.getFeb20DolorArticular());
        cv.put(Covid19DBConstants.feb20SecresionNasal, cuestionario.getFeb20SecresionNasal());
        cv.put(Covid19DBConstants.feb20DolorGarganta, cuestionario.getFeb20DolorGarganta());
        cv.put(Covid19DBConstants.feb20Tos, cuestionario.getFeb20Tos());
        cv.put(Covid19DBConstants.feb20DificultadResp, cuestionario.getFeb20DificultadResp());
        cv.put(Covid19DBConstants.feb20DolorPecho, cuestionario.getFeb20DolorPecho());
        cv.put(Covid19DBConstants.feb20NauseasVomito, cuestionario.getFeb20NauseasVomito());
        cv.put(Covid19DBConstants.feb20DolorCabeza, cuestionario.getFeb20DolorCabeza());
        cv.put(Covid19DBConstants.feb20DolorAbdominal, cuestionario.getFeb20DolorAbdominal());
        cv.put(Covid19DBConstants.feb20Diarrea, cuestionario.getFeb20Diarrea());
        cv.put(Covid19DBConstants.feb20DificultadDormir, cuestionario.getFeb20DificultadDormir());
        cv.put(Covid19DBConstants.feb20Debilidad, cuestionario.getFeb20Debilidad());
        cv.put(Covid19DBConstants.feb20PerdidaOlfatoGusto, cuestionario.getFeb20PerdidaOlfatoGusto());
        cv.put(Covid19DBConstants.feb20Mareo, cuestionario.getFeb20Mareo());
        cv.put(Covid19DBConstants.feb20Sarpullido, cuestionario.getFeb20Sarpullido());
        cv.put(Covid19DBConstants.feb20Desmayo, cuestionario.getFeb20Desmayo());
        cv.put(Covid19DBConstants.feb20QuedoCama, cuestionario.getFeb20QuedoCama());
        cv.put(Covid19DBConstants.padecidoCovid19, cuestionario.getPadecidoCovid19());
*/
        cv.put(Covid19DBConstants.e1SabeFIS, cuestionario.getE1SabeFIS());
        if (cuestionario.getE1Fis() != null) cv.put(Covid19DBConstants.e1FIS, cuestionario.getE1Fis().getTime());
        cv.put(Covid19DBConstants.e1MesInicioSintoma, cuestionario.getE1MesInicioSintoma());
        cv.put(Covid19DBConstants.e1AnioInicioSintoma, cuestionario.getE1AnioInicioSintoma());
        cv.put(Covid19DBConstants.e1ConoceLugarExposicion, cuestionario.getE1ConoceLugarExposicion());
        cv.put(Covid19DBConstants.e1LugarExposicion, cuestionario.getE1LugarExposicion());
        cv.put(Covid19DBConstants.e1BuscoAyuda, cuestionario.getE1BuscoAyuda());
        cv.put(Covid19DBConstants.e1DondeBuscoAyuda, cuestionario.getE1DondeBuscoAyuda());
        cv.put(Covid19DBConstants.e1NombreCentroSalud, cuestionario.getE1NombreCentroSalud());
        cv.put(Covid19DBConstants.e1NombreHospital, cuestionario.getE1NombreHospital());
        cv.put(Covid19DBConstants.e1RecibioSeguimiento, cuestionario.getE1RecibioSeguimiento());
        cv.put(Covid19DBConstants.e1TipoSeguimiento, cuestionario.getE1TipoSeguimiento());
        cv.put(Covid19DBConstants.e1TmpDespuesBuscoAyuda, cuestionario.getE1TmpDespuesBuscoAyuda());
        cv.put(Covid19DBConstants.e1UnaNocheHospital, cuestionario.getE1UnaNocheHospital());
        cv.put(Covid19DBConstants.e1QueHospital, cuestionario.getE1QueHospital());
        cv.put(Covid19DBConstants.e1SabeCuantasNoches, cuestionario.getE1SabeCuantasNoches());
        cv.put(Covid19DBConstants.e1CuantasNochesHosp, cuestionario.getE1CuantasNochesHosp());
        cv.put(Covid19DBConstants.e1SabeFechaAdmision, cuestionario.getE1SabeFechaAdmision());
        if (cuestionario.getE1FechaAdmisionHosp() != null) cv.put(Covid19DBConstants.e1FechaAdmisionHosp, cuestionario.getE1FechaAdmisionHosp().getTime());
        cv.put(Covid19DBConstants.e1SabeFechaAlta, cuestionario.getE1SabeFechaAlta());
        if (cuestionario.getE1FechaAltaHosp() != null) cv.put(Covid19DBConstants.e1FechaAltaHosp, cuestionario.getE1FechaAltaHosp().getTime());
        cv.put(Covid19DBConstants.e1UtilizoOxigeno, cuestionario.getE1UtilizoOxigeno());
        cv.put(Covid19DBConstants.e1EstuvoUCI, cuestionario.getE1EstuvoUCI());
        cv.put(Covid19DBConstants.e1FueIntubado, cuestionario.getE1FueIntubado());
        cv.put(Covid19DBConstants.e1RecuperadoCovid19, cuestionario.getE1RecuperadoCovid19());
        cv.put(Covid19DBConstants.e1TenidoFebricula, cuestionario.getE1TieneFebricula());
        cv.put(Covid19DBConstants.e1TenidoCansancio, cuestionario.getE1TieneCansancio());
        cv.put(Covid19DBConstants.e1TenidoDolorCabeza, cuestionario.getE1TieneDolorCabeza());
        cv.put(Covid19DBConstants.e1TenidoPerdidaOlfato, cuestionario.getE1TienePerdidaOlfato());
        cv.put(Covid19DBConstants.e1TenidoPerdidaGusto, cuestionario.getE1TienePerdidaGusto());
        cv.put(Covid19DBConstants.e1TenidoTos, cuestionario.getE1TieneTos());
        cv.put(Covid19DBConstants.e1TenidoDificultadRespirar, cuestionario.getE1TieneDificultadRespirar());
        cv.put(Covid19DBConstants.e1TenidoDolorPecho, cuestionario.getE1TieneDolorPecho());
        cv.put(Covid19DBConstants.e1TenidoPalpitaciones, cuestionario.getE1TienePalpitaciones());
        cv.put(Covid19DBConstants.e1TenidoDolorArticulaciones, cuestionario.getE1TieneDolorArticulaciones());
        cv.put(Covid19DBConstants.e1TenidoParalisis, cuestionario.getE1TieneParalisis());
        cv.put(Covid19DBConstants.e1TenidoMareos, cuestionario.getE1TieneMareos());
        cv.put(Covid19DBConstants.e1TenidoPensamientoNublado, cuestionario.getE1TienePensamientoNublado());
        cv.put(Covid19DBConstants.e1TenidoProblemasDormir, cuestionario.getE1TieneProblemasDormir());
        cv.put(Covid19DBConstants.e1TenidoDepresion, cuestionario.getE1TieneDepresion());
        cv.put(Covid19DBConstants.e1TenidoOtrosSintomas, cuestionario.getE1TieneOtrosSintomas());
        cv.put(Covid19DBConstants.e1CualesSintomas, cuestionario.getE1cualesSintomas());
        cv.put(Covid19DBConstants.e1SabeTiempoRecuperacion, cuestionario.getE1SabeTiempoRecuperacion());
        cv.put(Covid19DBConstants.e1TiempoRecuperacion, cuestionario.getE1TiempoRecuperacion());
        cv.put(Covid19DBConstants.e1TiempoRecuperacionEn, cuestionario.getE1TiempoRecuperacionEn());
        cv.put(Covid19DBConstants.e1SeveridadEnfermedad, cuestionario.getE1SeveridadEnfermedad());
        cv.put(Covid19DBConstants.e1TomoMedicamento, cuestionario.getE1TomoMedicamento());
        cv.put(Covid19DBConstants.e1QueMedicamento, cuestionario.getE1QueMedicamento());
        cv.put(Covid19DBConstants.e1OtroMedicamento, cuestionario.getE1OtroMedicamento());
        cv.put(Covid19DBConstants.e1OxigenoDomicilio, cuestionario.getE1OxigenoDomicilio());
        cv.put(Covid19DBConstants.e1TiempoOxigenoDom, cuestionario.getE1TiempoOxigenoDom());

        cv.put(Covid19DBConstants.e2SabeFIS, cuestionario.getE2SabeFIS());
        if (cuestionario.getE2Fis() != null) cv.put(Covid19DBConstants.e2FIS, cuestionario.getE2Fis().getTime());
        cv.put(Covid19DBConstants.e2MesInicioSintoma, cuestionario.getE2MesInicioSintoma());
        cv.put(Covid19DBConstants.e2AnioInicioSintoma, cuestionario.getE2AnioInicioSintoma());
        cv.put(Covid19DBConstants.e2ConoceLugarExposicion, cuestionario.getE2ConoceLugarExposicion());
        cv.put(Covid19DBConstants.e2LugarExposicion, cuestionario.getE2LugarExposicion());
        cv.put(Covid19DBConstants.e2BuscoAyuda, cuestionario.getE2BuscoAyuda());
        cv.put(Covid19DBConstants.e2DondeBuscoAyuda, cuestionario.getE2DondeBuscoAyuda());
        cv.put(Covid19DBConstants.e2NombreCentroSalud, cuestionario.getE2NombreCentroSalud());
        cv.put(Covid19DBConstants.e2NombreHospital, cuestionario.getE2NombreHospital());
        cv.put(Covid19DBConstants.e2RecibioSeguimiento, cuestionario.getE2RecibioSeguimiento());
        cv.put(Covid19DBConstants.e2TipoSeguimiento, cuestionario.getE2TipoSeguimiento());
        cv.put(Covid19DBConstants.e2TmpDespuesBuscoAyuda, cuestionario.getE2TmpDespuesBuscoAyuda());
        cv.put(Covid19DBConstants.e2UnaNocheHospital, cuestionario.getE2UnaNocheHospital());
        cv.put(Covid19DBConstants.e2QueHospital, cuestionario.getE2QueHospital());
        cv.put(Covid19DBConstants.e2SabeCuantasNoches, cuestionario.getE2SabeCuantasNoches());
        cv.put(Covid19DBConstants.e2CuantasNochesHosp, cuestionario.getE2CuantasNochesHosp());
        cv.put(Covid19DBConstants.e2SabeFechaAdmision, cuestionario.getE2SabeFechaAdmision());
        if (cuestionario.getE2FechaAdmisionHosp() != null) cv.put(Covid19DBConstants.e2FechaAdmisionHosp, cuestionario.getE2FechaAdmisionHosp().getTime());
        cv.put(Covid19DBConstants.e2SabeFechaAlta, cuestionario.getE2SabeFechaAlta());
        if (cuestionario.getE2FechaAltaHosp() != null) cv.put(Covid19DBConstants.e2FechaAltaHosp, cuestionario.getE2FechaAltaHosp().getTime());
        cv.put(Covid19DBConstants.e2UtilizoOxigeno, cuestionario.getE2UtilizoOxigeno());
        cv.put(Covid19DBConstants.e2EstuvoUCI, cuestionario.getE2EstuvoUCI());
        cv.put(Covid19DBConstants.e2FueIntubado, cuestionario.getE2FueIntubado());
        cv.put(Covid19DBConstants.e2RecuperadoCovid19, cuestionario.getE2RecuperadoCovid19());
        cv.put(Covid19DBConstants.e2TenidoFebricula, cuestionario.getE2TieneFebricula());
        cv.put(Covid19DBConstants.e2TenidoCansancio, cuestionario.getE2TieneCansancio());
        cv.put(Covid19DBConstants.e2TenidoDolorCabeza, cuestionario.getE2TieneDolorCabeza());
        cv.put(Covid19DBConstants.e2TenidoPerdidaOlfato, cuestionario.getE2TienePerdidaOlfato());
        cv.put(Covid19DBConstants.e2TenidoPerdidaGusto, cuestionario.getE2TienePerdidaGusto());
        cv.put(Covid19DBConstants.e2TenidoTos, cuestionario.getE2TieneTos());
        cv.put(Covid19DBConstants.e2TenidoDificultadRespirar, cuestionario.getE2TieneDificultadRespirar());
        cv.put(Covid19DBConstants.e2TenidoDolorPecho, cuestionario.getE2TieneDolorPecho());
        cv.put(Covid19DBConstants.e2TenidoPalpitaciones, cuestionario.getE2TienePalpitaciones());
        cv.put(Covid19DBConstants.e2TenidoDolorArticulaciones, cuestionario.getE2TieneDolorArticulaciones());
        cv.put(Covid19DBConstants.e2TenidoParalisis, cuestionario.getE2TieneParalisis());
        cv.put(Covid19DBConstants.e2TenidoMareos, cuestionario.getE2TieneMareos());
        cv.put(Covid19DBConstants.e2TenidoPensamientoNublado, cuestionario.getE2TienePensamientoNublado());
        cv.put(Covid19DBConstants.e2TenidoProblemasDormir, cuestionario.getE2TieneProblemasDormir());
        cv.put(Covid19DBConstants.e2TenidoDepresion, cuestionario.getE2TieneDepresion());
        cv.put(Covid19DBConstants.e2TenidoOtrosSintomas, cuestionario.getE2TieneOtrosSintomas());
        cv.put(Covid19DBConstants.e2CualesSintomas, cuestionario.getE2cualesSintomas());
        cv.put(Covid19DBConstants.e2SabeTiempoRecuperacion, cuestionario.getE2SabeTiempoRecuperacion());
        cv.put(Covid19DBConstants.e2TiempoRecuperacion, cuestionario.getE2TiempoRecuperacion());
        cv.put(Covid19DBConstants.e2TiempoRecuperacionEn, cuestionario.getE2TiempoRecuperacionEn());
        cv.put(Covid19DBConstants.e2SeveridadEnfermedad, cuestionario.getE2SeveridadEnfermedad());
        cv.put(Covid19DBConstants.e2TomoMedicamento, cuestionario.getE2TomoMedicamento());
        cv.put(Covid19DBConstants.e2QueMedicamento, cuestionario.getE2QueMedicamento());
        cv.put(Covid19DBConstants.e2OtroMedicamento, cuestionario.getE2OtroMedicamento());
        cv.put(Covid19DBConstants.e2OxigenoDomicilio, cuestionario.getE2OxigenoDomicilio());
        cv.put(Covid19DBConstants.e2TiempoOxigenoDom, cuestionario.getE2TiempoOxigenoDom());

        cv.put(Covid19DBConstants.e3SabeFIS, cuestionario.getE3SabeFIS());
        if (cuestionario.getE3Fis() != null) cv.put(Covid19DBConstants.e3FIS, cuestionario.getE3Fis().getTime());
        cv.put(Covid19DBConstants.e3MesInicioSintoma, cuestionario.getE3MesInicioSintoma());
        cv.put(Covid19DBConstants.e3AnioInicioSintoma, cuestionario.getE3AnioInicioSintoma());
        cv.put(Covid19DBConstants.e3ConoceLugarExposicion, cuestionario.getE3ConoceLugarExposicion());
        cv.put(Covid19DBConstants.e3LugarExposicion, cuestionario.getE3LugarExposicion());
        cv.put(Covid19DBConstants.e3BuscoAyuda, cuestionario.getE3BuscoAyuda());
        cv.put(Covid19DBConstants.e3DondeBuscoAyuda, cuestionario.getE3DondeBuscoAyuda());
        cv.put(Covid19DBConstants.e3NombreCentroSalud, cuestionario.getE3NombreCentroSalud());
        cv.put(Covid19DBConstants.e3NombreHospital, cuestionario.getE3NombreHospital());
        cv.put(Covid19DBConstants.e3RecibioSeguimiento, cuestionario.getE3RecibioSeguimiento());
        cv.put(Covid19DBConstants.e3TipoSeguimiento, cuestionario.getE3TipoSeguimiento());
        cv.put(Covid19DBConstants.e3TmpDespuesBuscoAyuda, cuestionario.getE3TmpDespuesBuscoAyuda());
        cv.put(Covid19DBConstants.e3UnaNocheHospital, cuestionario.getE3UnaNocheHospital());
        cv.put(Covid19DBConstants.e3QueHospital, cuestionario.getE3QueHospital());
        cv.put(Covid19DBConstants.e3SabeCuantasNoches, cuestionario.getE3SabeCuantasNoches());
        cv.put(Covid19DBConstants.e3CuantasNochesHosp, cuestionario.getE3CuantasNochesHosp());
        cv.put(Covid19DBConstants.e3SabeFechaAdmision, cuestionario.getE3SabeFechaAdmision());
        if (cuestionario.getE3FechaAdmisionHosp() != null) cv.put(Covid19DBConstants.e3FechaAdmisionHosp, cuestionario.getE3FechaAdmisionHosp().getTime());
        cv.put(Covid19DBConstants.e3SabeFechaAlta, cuestionario.getE3SabeFechaAlta());
        if (cuestionario.getE3FechaAltaHosp() != null) cv.put(Covid19DBConstants.e3FechaAltaHosp, cuestionario.getE3FechaAltaHosp().getTime());
        cv.put(Covid19DBConstants.e3UtilizoOxigeno, cuestionario.getE3UtilizoOxigeno());
        cv.put(Covid19DBConstants.e3EstuvoUCI, cuestionario.getE3EstuvoUCI());
        cv.put(Covid19DBConstants.e3FueIntubado, cuestionario.getE3FueIntubado());
        cv.put(Covid19DBConstants.e3RecuperadoCovid19, cuestionario.getE3RecuperadoCovid19());
        cv.put(Covid19DBConstants.e3TenidoFebricula, cuestionario.getE3TieneFebricula());
        cv.put(Covid19DBConstants.e3TenidoCansancio, cuestionario.getE3TieneCansancio());
        cv.put(Covid19DBConstants.e3TenidoDolorCabeza, cuestionario.getE3TieneDolorCabeza());
        cv.put(Covid19DBConstants.e3TenidoPerdidaOlfato, cuestionario.getE3TienePerdidaOlfato());
        cv.put(Covid19DBConstants.e3TenidoPerdidaGusto, cuestionario.getE3TienePerdidaGusto());
        cv.put(Covid19DBConstants.e3TenidoTos, cuestionario.getE3TieneTos());
        cv.put(Covid19DBConstants.e3TenidoDificultadRespirar, cuestionario.getE3TieneDificultadRespirar());
        cv.put(Covid19DBConstants.e3TenidoDolorPecho, cuestionario.getE3TieneDolorPecho());
        cv.put(Covid19DBConstants.e3TenidoPalpitaciones, cuestionario.getE3TienePalpitaciones());
        cv.put(Covid19DBConstants.e3TenidoDolorArticulaciones, cuestionario.getE3TieneDolorArticulaciones());
        cv.put(Covid19DBConstants.e3TenidoParalisis, cuestionario.getE3TieneParalisis());
        cv.put(Covid19DBConstants.e3TenidoMareos, cuestionario.getE3TieneMareos());
        cv.put(Covid19DBConstants.e3TenidoPensamientoNublado, cuestionario.getE3TienePensamientoNublado());
        cv.put(Covid19DBConstants.e3TenidoProblemasDormir, cuestionario.getE3TieneProblemasDormir());
        cv.put(Covid19DBConstants.e3TenidoDepresion, cuestionario.getE3TieneDepresion());
        cv.put(Covid19DBConstants.e3TenidoOtrosSintomas, cuestionario.getE3TieneOtrosSintomas());
        cv.put(Covid19DBConstants.e3CualesSintomas, cuestionario.getE3cualesSintomas());
        cv.put(Covid19DBConstants.e3SabeTiempoRecuperacion, cuestionario.getE3SabeTiempoRecuperacion());
        cv.put(Covid19DBConstants.e3TiempoRecuperacion, cuestionario.getE3TiempoRecuperacion());
        cv.put(Covid19DBConstants.e3TiempoRecuperacionEn, cuestionario.getE3TiempoRecuperacionEn());
        cv.put(Covid19DBConstants.e3SeveridadEnfermedad, cuestionario.getE3SeveridadEnfermedad());
        cv.put(Covid19DBConstants.e3TomoMedicamento, cuestionario.getE3TomoMedicamento());
        cv.put(Covid19DBConstants.e3QueMedicamento, cuestionario.getE3QueMedicamento());
        cv.put(Covid19DBConstants.e3OtroMedicamento, cuestionario.getE3OtroMedicamento());
        cv.put(Covid19DBConstants.e3OxigenoDomicilio, cuestionario.getE3OxigenoDomicilio());
        cv.put(Covid19DBConstants.e3TiempoOxigenoDom, cuestionario.getE3TiempoOxigenoDom());

        cv.put(Covid19DBConstants.padeceEnfisema, cuestionario.getPadeceEnfisema());
        cv.put(Covid19DBConstants.padeceAsma, cuestionario.getPadeceAsma());
        cv.put(Covid19DBConstants.padeceDiabetes, cuestionario.getPadeceDiabetes());
        cv.put(Covid19DBConstants.padeceEnfCoronaria, cuestionario.getPadeceEnfCoronaria());
        cv.put(Covid19DBConstants.padecePresionAlta, cuestionario.getPadecePresionAlta());
        cv.put(Covid19DBConstants.padeceEnfHigado, cuestionario.getPadeceEnfHigado());
        cv.put(Covid19DBConstants.padeceEnfRenal, cuestionario.getPadeceEnfRenal());
        cv.put(Covid19DBConstants.padeceInfartoDerrameCer, cuestionario.getPadeceInfartoDerrameCer());
        cv.put(Covid19DBConstants.padeceCancer, cuestionario.getPadeceCancer());
        cv.put(Covid19DBConstants.padeceCondicionInmuno, cuestionario.getPadeceCondicionInmuno());
        cv.put(Covid19DBConstants.padeceEnfAutoinmune, cuestionario.getPadeceEnfAutoinmune());
        cv.put(Covid19DBConstants.padeceDiscapacidadFis, cuestionario.getPadeceDiscapacidadFis());
        cv.put(Covid19DBConstants.padeceCondPsicPsiq, cuestionario.getPadeceCondPsicPsiq());
        cv.put(Covid19DBConstants.padeceOtraCondicion, cuestionario.getPadeceOtraCondicion());
        cv.put(Covid19DBConstants.queOtraCondicion, cuestionario.getQueOtraCondicion());
        cv.put(Covid19DBConstants.fumado, cuestionario.getFumado());
        cv.put(Covid19DBConstants.fumadoCienCigarrillos, cuestionario.getFumadoCienCigarrillos());

        cv.put(Covid19DBConstants.e1FumadoPrevioEnfermedad, cuestionario.getE1FumadoPrevioEnfermedad());
        cv.put(Covid19DBConstants.e1FumaActualmente, cuestionario.getE1FumaActualmente());
        //MA2021
        cv.put(Covid19DBConstants.e1Embarazada, cuestionario.getE1Embarazada());
        cv.put(Covid19DBConstants.e1RecuerdaSemanasEmb, cuestionario.getE1RecuerdaSemanasEmb());
        cv.put(Covid19DBConstants.e1SemanasEmbarazo, cuestionario.getE1SemanasEmbarazo());
        cv.put(Covid19DBConstants.e1FinalEmbarazo, cuestionario.getE1FinalEmbarazo());
        cv.put(Covid19DBConstants.e1OtroFinalEmbarazo, cuestionario.getE1OtroFinalEmbarazo());
        cv.put(Covid19DBConstants.e1DabaPecho, cuestionario.getE1DabaPecho());

        cv.put(Covid19DBConstants.e2FumadoPrevioEnfermedad, cuestionario.getE2FumadoPrevioEnfermedad());
        cv.put(Covid19DBConstants.e2FumaActualmente, cuestionario.getE2FumaActualmente());
        cv.put(Covid19DBConstants.e2Embarazada, cuestionario.getE2Embarazada());
        cv.put(Covid19DBConstants.e2RecuerdaSemanasEmb, cuestionario.getE2RecuerdaSemanasEmb());
        cv.put(Covid19DBConstants.e2SemanasEmbarazo, cuestionario.getE2SemanasEmbarazo());
        cv.put(Covid19DBConstants.e2FinalEmbarazo, cuestionario.getE2FinalEmbarazo());
        cv.put(Covid19DBConstants.e2OtroFinalEmbarazo, cuestionario.getE2OtroFinalEmbarazo());
        cv.put(Covid19DBConstants.e2DabaPecho, cuestionario.getE2DabaPecho());

        cv.put(Covid19DBConstants.e3FumadoPrevioEnfermedad, cuestionario.getE3FumadoPrevioEnfermedad());
        cv.put(Covid19DBConstants.e3FumaActualmente, cuestionario.getE3FumaActualmente());
        cv.put(Covid19DBConstants.e3Embarazada, cuestionario.getE3Embarazada());
        cv.put(Covid19DBConstants.e3RecuerdaSemanasEmb, cuestionario.getE3RecuerdaSemanasEmb());
        cv.put(Covid19DBConstants.e3SemanasEmbarazo, cuestionario.getE3SemanasEmbarazo());
        cv.put(Covid19DBConstants.e3FinalEmbarazo, cuestionario.getE3FinalEmbarazo());
        cv.put(Covid19DBConstants.e3OtroFinalEmbarazo, cuestionario.getE3OtroFinalEmbarazo());
        cv.put(Covid19DBConstants.e3DabaPecho, cuestionario.getE3DabaPecho());

        cv.put(Covid19DBConstants.trabajadorSalud, cuestionario.getTrabajadorSalud());
        cv.put(Covid19DBConstants.periodoSintomas, cuestionario.getPeriodoSintomas());
        //Muestreo Familia Nov 2021
        cv.put(Covid19DBConstants.enfermoCovid19, cuestionario.getEnfermoCovid19());
        cv.put(Covid19DBConstants.cuantasVecesEnfermo, cuestionario.getCuantasVecesEnfermo());
        cv.put(Covid19DBConstants.sabeEvento1, cuestionario.getSabeEvento1());
        if (cuestionario.getEvento1() != null) cv.put(Covid19DBConstants.evento1, cuestionario.getEvento1().getTime());
        cv.put(Covid19DBConstants.anioEvento1, cuestionario.getAnioEvento1());
        cv.put(Covid19DBConstants.mesEvento1, cuestionario.getMesEvento1());
        cv.put(Covid19DBConstants.sabeEvento2, cuestionario.getSabeEvento2());
        if (cuestionario.getEvento2() != null) cv.put(Covid19DBConstants.evento2, cuestionario.getEvento2().getTime());
        cv.put(Covid19DBConstants.anioEvento2, cuestionario.getAnioEvento2());
        cv.put(Covid19DBConstants.mesEvento2, cuestionario.getMesEvento2());
        cv.put(Covid19DBConstants.sabeEvento3, cuestionario.getSabeEvento3());
        if (cuestionario.getEvento3() != null) cv.put(Covid19DBConstants.evento3, cuestionario.getEvento3().getTime());
        cv.put(Covid19DBConstants.anioEvento3, cuestionario.getAnioEvento3());
        cv.put(Covid19DBConstants.mesEvento3, cuestionario.getMesEvento3());
        cv.put(Covid19DBConstants.e1Febricula, cuestionario.getE1Febricula());
        cv.put(Covid19DBConstants.e1Fiebre, cuestionario.getE1Fiebre());
        cv.put(Covid19DBConstants.e1Escalofrio, cuestionario.getE1Escalofrio());
        cv.put(Covid19DBConstants.e1TemblorEscalofrio, cuestionario.getE1TemblorEscalofrio());
        cv.put(Covid19DBConstants.e1DolorMuscular, cuestionario.getE1DolorMuscular());
        cv.put(Covid19DBConstants.e1DolorArticular, cuestionario.getE1DolorArticular());
        cv.put(Covid19DBConstants.e1SecresionNasal, cuestionario.getE1SecresionNasal());
        cv.put(Covid19DBConstants.e1DolorGarganta, cuestionario.getE1DolorGarganta());
        cv.put(Covid19DBConstants.e1Tos, cuestionario.getE1Tos());
        cv.put(Covid19DBConstants.e1DificultadResp, cuestionario.getE1DificultadResp());
        cv.put(Covid19DBConstants.e1DolorPecho, cuestionario.getE1DolorPecho());
        cv.put(Covid19DBConstants.e1NauseasVomito, cuestionario.getE1NauseasVomito());
        cv.put(Covid19DBConstants.e1DolorCabeza, cuestionario.getE1DolorCabeza());
        cv.put(Covid19DBConstants.e1DolorAbdominal, cuestionario.getE1DolorAbdominal());
        cv.put(Covid19DBConstants.e1Diarrea, cuestionario.getE1Diarrea());
        cv.put(Covid19DBConstants.e1DificultadDormir, cuestionario.getE1DificultadDormir());
        cv.put(Covid19DBConstants.e1Debilidad, cuestionario.getE1Debilidad());
        cv.put(Covid19DBConstants.e1PerdidaOlfatoGusto, cuestionario.getE1PerdidaOlfatoGusto());
        cv.put(Covid19DBConstants.e1Mareo, cuestionario.getE1Mareo());
        cv.put(Covid19DBConstants.e1Sarpullido, cuestionario.getE1Sarpullido());
        cv.put(Covid19DBConstants.e1Desmayo, cuestionario.getE1Desmayo());
        cv.put(Covid19DBConstants.e1QuedoCama, cuestionario.getE1QuedoCama());
        cv.put(Covid19DBConstants.e2Febricula, cuestionario.getE2Febricula());
        cv.put(Covid19DBConstants.e2Fiebre, cuestionario.getE2Fiebre());
        cv.put(Covid19DBConstants.e2Escalofrio, cuestionario.getE2Escalofrio());
        cv.put(Covid19DBConstants.e2TemblorEscalofrio, cuestionario.getE2TemblorEscalofrio());
        cv.put(Covid19DBConstants.e2DolorMuscular, cuestionario.getE2DolorMuscular());
        cv.put(Covid19DBConstants.e2DolorArticular, cuestionario.getE2DolorArticular());
        cv.put(Covid19DBConstants.e2SecresionNasal, cuestionario.getE2SecresionNasal());
        cv.put(Covid19DBConstants.e2DolorGarganta, cuestionario.getE2DolorGarganta());
        cv.put(Covid19DBConstants.e2Tos, cuestionario.getE2Tos());
        cv.put(Covid19DBConstants.e2DificultadResp, cuestionario.getE2DificultadResp());
        cv.put(Covid19DBConstants.e2DolorPecho, cuestionario.getE2DolorPecho());
        cv.put(Covid19DBConstants.e2NauseasVomito, cuestionario.getE2NauseasVomito());
        cv.put(Covid19DBConstants.e2DolorCabeza, cuestionario.getE2DolorCabeza());
        cv.put(Covid19DBConstants.e2DolorAbdominal, cuestionario.getE2DolorAbdominal());
        cv.put(Covid19DBConstants.e2Diarrea, cuestionario.getE2Diarrea());
        cv.put(Covid19DBConstants.e2DificultadDormir, cuestionario.getE2DificultadDormir());
        cv.put(Covid19DBConstants.e2Debilidad, cuestionario.getE2Debilidad());
        cv.put(Covid19DBConstants.e2PerdidaOlfatoGusto, cuestionario.getE2PerdidaOlfatoGusto());
        cv.put(Covid19DBConstants.e2Mareo, cuestionario.getE2Mareo());
        cv.put(Covid19DBConstants.e2Sarpullido, cuestionario.getE2Sarpullido());
        cv.put(Covid19DBConstants.e2Desmayo, cuestionario.getE2Desmayo());
        cv.put(Covid19DBConstants.e2QuedoCama, cuestionario.getE2QuedoCama());
        cv.put(Covid19DBConstants.e3Febricula, cuestionario.getE3Febricula());
        cv.put(Covid19DBConstants.e3Fiebre, cuestionario.getE3Fiebre());
        cv.put(Covid19DBConstants.e3Escalofrio, cuestionario.getE3Escalofrio());
        cv.put(Covid19DBConstants.e3TemblorEscalofrio, cuestionario.getE3TemblorEscalofrio());
        cv.put(Covid19DBConstants.e3DolorMuscular, cuestionario.getE3DolorMuscular());
        cv.put(Covid19DBConstants.e3DolorArticular, cuestionario.getE3DolorArticular());
        cv.put(Covid19DBConstants.e3SecresionNasal, cuestionario.getE3SecresionNasal());
        cv.put(Covid19DBConstants.e3DolorGarganta, cuestionario.getE3DolorGarganta());
        cv.put(Covid19DBConstants.e3Tos, cuestionario.getE3Tos());
        cv.put(Covid19DBConstants.e3DificultadResp, cuestionario.getE3DificultadResp());
        cv.put(Covid19DBConstants.e3DolorPecho, cuestionario.getE3DolorPecho());
        cv.put(Covid19DBConstants.e3NauseasVomito, cuestionario.getE3NauseasVomito());
        cv.put(Covid19DBConstants.e3DolorCabeza, cuestionario.getE3DolorCabeza());
        cv.put(Covid19DBConstants.e3DolorAbdominal, cuestionario.getE3DolorAbdominal());
        cv.put(Covid19DBConstants.e3Diarrea, cuestionario.getE3Diarrea());
        cv.put(Covid19DBConstants.e3DificultadDormir, cuestionario.getE3DificultadDormir());
        cv.put(Covid19DBConstants.e3Debilidad, cuestionario.getE3Debilidad());
        cv.put(Covid19DBConstants.e3PerdidaOlfatoGusto, cuestionario.getE3PerdidaOlfatoGusto());
        cv.put(Covid19DBConstants.e3Mareo, cuestionario.getE3Mareo());
        cv.put(Covid19DBConstants.e3Sarpullido, cuestionario.getE3Sarpullido());
        cv.put(Covid19DBConstants.e3Desmayo, cuestionario.getE3Desmayo());
        cv.put(Covid19DBConstants.e3QuedoCama, cuestionario.getE3QuedoCama());
        cv.put(Covid19DBConstants.vacunadoCovid19, cuestionario.getVacunadoCovid19());
        cv.put(Covid19DBConstants.muestraTarjetaVac, cuestionario.getMuestraTarjetaVac());
        cv.put(Covid19DBConstants.sabeNombreVacuna, cuestionario.getSabeNombreVacuna());
        cv.put(Covid19DBConstants.nombreVacuna, cuestionario.getNombreVacuna());
        cv.put(Covid19DBConstants.anioVacuna, cuestionario.getAnioVacuna());
        cv.put(Covid19DBConstants.mesVacuna, cuestionario.getMesVacuna());
        cv.put(Covid19DBConstants.cuantasDosis, cuestionario.getCuantasDosis());
        cv.put(Covid19DBConstants.nombreDosis1, cuestionario.getNombreDosis1());
        cv.put(Covid19DBConstants.otraVacunaDosis1, cuestionario.getOtraVacunaDosis1());
        cv.put(Covid19DBConstants.loteDosis1, cuestionario.getLoteDosis1());
        if (cuestionario.getFechaDosis1() != null) cv.put(Covid19DBConstants.fechaDosis1, cuestionario.getFechaDosis1().getTime());
        cv.put(Covid19DBConstants.nombreDosis2, cuestionario.getNombreDosis2());
        cv.put(Covid19DBConstants.otraVacunaDosis2, cuestionario.getOtraVacunaDosis2());
        cv.put(Covid19DBConstants.loteDosis2, cuestionario.getLoteDosis2());
        if (cuestionario.getFechaDosis2() != null) cv.put(Covid19DBConstants.fechaDosis2, cuestionario.getFechaDosis2().getTime());
        cv.put(Covid19DBConstants.nombreDosis3, cuestionario.getNombreDosis3());
        cv.put(Covid19DBConstants.otraVacunaDosis3, cuestionario.getOtraVacunaDosis3());
        cv.put(Covid19DBConstants.loteDosis3, cuestionario.getLoteDosis3());
        if (cuestionario.getFechaDosis3() != null) cv.put(Covid19DBConstants.fechaDosis3, cuestionario.getFechaDosis3().getTime());

        cv.put(Covid19DBConstants.presentoSintomasDosis1, cuestionario.getPresentoSintomasDosis1());
        cv.put(Covid19DBConstants.dolorSitioDosis1, cuestionario.getDolorSitioDosis1());
        cv.put(Covid19DBConstants.fiebreDosis1, cuestionario.getFiebreDosis1());
        cv.put(Covid19DBConstants.cansancioDosis1, cuestionario.getCansancioDosis1());
        cv.put(Covid19DBConstants.dolorCabezaDosis1, cuestionario.getDolorCabezaDosis1());
        cv.put(Covid19DBConstants.diarreaDosis1, cuestionario.getDiarreaDosis1());
        cv.put(Covid19DBConstants.vomitoDosis1, cuestionario.getVomitoDosis1());
        cv.put(Covid19DBConstants.dolorMuscularDosis1, cuestionario.getDolorMuscularDosis1());
        cv.put(Covid19DBConstants.escalofriosDosis1, cuestionario.getEscalofriosDosis1());
        cv.put(Covid19DBConstants.reaccionAlergicaDosis1, cuestionario.getReaccionAlergicaDosis1());
        cv.put(Covid19DBConstants.infeccionSitioDosis1, cuestionario.getInfeccionSitioDosis1());
        cv.put(Covid19DBConstants.nauseasDosis1, cuestionario.getNauseasDosis1());
        cv.put(Covid19DBConstants.bultosDosis1, cuestionario.getBultosDosis1());
        cv.put(Covid19DBConstants.otrosDosis1, cuestionario.getOtrosDosis1());
        cv.put(Covid19DBConstants.desOtrosDosis1, cuestionario.getDesOtrosDosis1());

        cv.put(Covid19DBConstants.presentoSintomasDosis2, cuestionario.getPresentoSintomasDosis2());
        cv.put(Covid19DBConstants.dolorSitioDosis2, cuestionario.getDolorSitioDosis2());
        cv.put(Covid19DBConstants.fiebreDosis2, cuestionario.getFiebreDosis2());
        cv.put(Covid19DBConstants.cansancioDosis2, cuestionario.getCansancioDosis2());
        cv.put(Covid19DBConstants.dolorCabezaDosis2, cuestionario.getDolorCabezaDosis2());
        cv.put(Covid19DBConstants.diarreaDosis2, cuestionario.getDiarreaDosis2());
        cv.put(Covid19DBConstants.vomitoDosis2, cuestionario.getVomitoDosis2());
        cv.put(Covid19DBConstants.dolorMuscularDosis2, cuestionario.getDolorMuscularDosis2());
        cv.put(Covid19DBConstants.escalofriosDosis2, cuestionario.getEscalofriosDosis2());
        cv.put(Covid19DBConstants.reaccionAlergicaDosis2, cuestionario.getReaccionAlergicaDosis2());
        cv.put(Covid19DBConstants.infeccionSitioDosis2, cuestionario.getInfeccionSitioDosis2());
        cv.put(Covid19DBConstants.nauseasDosis2, cuestionario.getNauseasDosis2());
        cv.put(Covid19DBConstants.bultosDosis2, cuestionario.getBultosDosis2());
        cv.put(Covid19DBConstants.otrosDosis2, cuestionario.getOtrosDosis2());
        cv.put(Covid19DBConstants.desOtrosDosis2, cuestionario.getDesOtrosDosis2());

        cv.put(Covid19DBConstants.presentoSintomasDosis3, cuestionario.getPresentoSintomasDosis3());
        cv.put(Covid19DBConstants.dolorSitioDosis3, cuestionario.getDolorSitioDosis3());
        cv.put(Covid19DBConstants.fiebreDosis3, cuestionario.getFiebreDosis3());
        cv.put(Covid19DBConstants.cansancioDosis3, cuestionario.getCansancioDosis3());
        cv.put(Covid19DBConstants.dolorCabezaDosis3, cuestionario.getDolorCabezaDosis3());
        cv.put(Covid19DBConstants.diarreaDosis3, cuestionario.getDiarreaDosis3());
        cv.put(Covid19DBConstants.vomitoDosis3, cuestionario.getVomitoDosis3());
        cv.put(Covid19DBConstants.dolorMuscularDosis3, cuestionario.getDolorMuscularDosis3());
        cv.put(Covid19DBConstants.escalofriosDosis3, cuestionario.getEscalofriosDosis3());
        cv.put(Covid19DBConstants.reaccionAlergicaDosis3, cuestionario.getReaccionAlergicaDosis3());
        cv.put(Covid19DBConstants.infeccionSitioDosis3, cuestionario.getInfeccionSitioDosis3());
        cv.put(Covid19DBConstants.nauseasDosis3, cuestionario.getNauseasDosis3());
        cv.put(Covid19DBConstants.bultosDosis3, cuestionario.getBultosDosis3());
        cv.put(Covid19DBConstants.otrosDosis3, cuestionario.getOtrosDosis3());
        cv.put(Covid19DBConstants.desOtrosDosis3, cuestionario.getDesOtrosDosis3());

        cv.put(Covid19DBConstants.covid19PosteriorVacuna, cuestionario.getCovid19PosteriorVacuna());
        cv.put(Covid19DBConstants.sabeFechaEnfPostVac, cuestionario.getSabeFechaEnfPostVac());
        if (cuestionario.getFechaEnfPostVac() != null) cv.put(Covid19DBConstants.fechaEnfPostVac, cuestionario.getFechaEnfPostVac().getTime());
        cv.put(Covid19DBConstants.anioEnfPostVac, cuestionario.getAnioEnfPostVac());
        cv.put(Covid19DBConstants.mesEnfPostVac, cuestionario.getMesEnfPostVac());
        cv.put(Covid19DBConstants.fechaEventoEnfermoPostVac, cuestionario.getFechaEventoEnfermoPostVac());

        if (cuestionario.getRecordDate() != null) cv.put(MainDBConstants.recordDate, cuestionario.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, cuestionario.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(cuestionario.getPasive()));
        cv.put(MainDBConstants.estado, String.valueOf(cuestionario.getEstado()));
        cv.put(MainDBConstants.deviceId, cuestionario.getDeviceid());
        return cv;
    }

    public static CuestionarioCovid19 crearCuestionarioCovid19(Cursor cursor){
        CuestionarioCovid19 cuestionarioCovid19 = new CuestionarioCovid19();

        cuestionarioCovid19.setCodigo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.codigo)));
        cuestionarioCovid19.setParticipante(null);
/*        cuestionarioCovid19.setFeb20Febricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Febricula)));
        cuestionarioCovid19.setFeb20Fiebre(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Fiebre)));
        cuestionarioCovid19.setFeb20Escalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Escalofrio)));
        cuestionarioCovid19.setFeb20TemblorEscalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20TemblorEscalofrio)));
        cuestionarioCovid19.setFeb20DolorMuscular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DolorMuscular)));
        cuestionarioCovid19.setFeb20DolorArticular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DolorArticular)));
        cuestionarioCovid19.setFeb20SecresionNasal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20SecresionNasal)));
        cuestionarioCovid19.setFeb20DolorGarganta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DolorGarganta)));
        cuestionarioCovid19.setFeb20Tos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Tos)));
        cuestionarioCovid19.setFeb20DificultadResp(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DificultadResp)));
        cuestionarioCovid19.setFeb20DolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DolorPecho)));
        cuestionarioCovid19.setFeb20NauseasVomito(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20NauseasVomito)));
        cuestionarioCovid19.setFeb20DolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DolorCabeza)));
        cuestionarioCovid19.setFeb20DolorAbdominal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DolorAbdominal)));
        cuestionarioCovid19.setFeb20Diarrea(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Diarrea)));
        cuestionarioCovid19.setFeb20DificultadDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20DificultadDormir)));
        cuestionarioCovid19.setFeb20Debilidad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Debilidad)));
        cuestionarioCovid19.setFeb20PerdidaOlfatoGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20PerdidaOlfatoGusto)));
        cuestionarioCovid19.setFeb20Mareo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Mareo)));
        cuestionarioCovid19.setFeb20Sarpullido(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Sarpullido)));
        cuestionarioCovid19.setFeb20Desmayo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20Desmayo)));
        cuestionarioCovid19.setFeb20QuedoCama(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.feb20QuedoCama)));
        cuestionarioCovid19.setPadecidoCovid19(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padecidoCovid19)));
*/
        cuestionarioCovid19.setE1SabeFIS(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SabeFIS)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1FIS))>0) cuestionarioCovid19.setE1Fis(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1FIS))));
        cuestionarioCovid19.setE1MesInicioSintoma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1MesInicioSintoma)));
        cuestionarioCovid19.setE1AnioInicioSintoma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1AnioInicioSintoma)));
        cuestionarioCovid19.setE1ConoceLugarExposicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1ConoceLugarExposicion)));
        cuestionarioCovid19.setE1LugarExposicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1LugarExposicion)));
        cuestionarioCovid19.setE1BuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1BuscoAyuda)));
        cuestionarioCovid19.setE1DondeBuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DondeBuscoAyuda)));
        cuestionarioCovid19.setE1NombreCentroSalud(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1NombreCentroSalud)));
        cuestionarioCovid19.setE1NombreHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1NombreHospital)));
        cuestionarioCovid19.setE1RecibioSeguimiento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1RecibioSeguimiento)));
        cuestionarioCovid19.setE1TipoSeguimiento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TipoSeguimiento)));
        cuestionarioCovid19.setE1TmpDespuesBuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TmpDespuesBuscoAyuda)));
        cuestionarioCovid19.setE1UnaNocheHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1UnaNocheHospital)));
        cuestionarioCovid19.setE1QueHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1QueHospital)));
        cuestionarioCovid19.setE1SabeCuantasNoches(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SabeCuantasNoches)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1CuantasNochesHosp))>0) cuestionarioCovid19.setE1CuantasNochesHosp(cursor.getInt(cursor.getColumnIndex(Covid19DBConstants.e1CuantasNochesHosp)));
        cuestionarioCovid19.setE1SabeFechaAdmision(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SabeFechaAdmision)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1FechaAdmisionHosp))>0) cuestionarioCovid19.setE1FechaAdmisionHosp(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1FechaAdmisionHosp))));
        cuestionarioCovid19.setE1SabeFechaAlta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SabeFechaAlta)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1FechaAltaHosp))>0) cuestionarioCovid19.setE1FechaAltaHosp(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1FechaAltaHosp))));
        cuestionarioCovid19.setE1UtilizoOxigeno(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1UtilizoOxigeno)));
        cuestionarioCovid19.setE1EstuvoUCI(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1EstuvoUCI)));
        cuestionarioCovid19.setE1FueIntubado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1FueIntubado)));
        cuestionarioCovid19.setE1RecuperadoCovid19(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1RecuperadoCovid19)));
        cuestionarioCovid19.setE1TieneFebricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoFebricula)));
        cuestionarioCovid19.setE1TieneCansancio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoCansancio)));
        cuestionarioCovid19.setE1TieneDolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoDolorCabeza)));
        cuestionarioCovid19.setE1TienePerdidaOlfato(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoPerdidaOlfato)));
        cuestionarioCovid19.setE1TienePerdidaGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoPerdidaGusto)));
        cuestionarioCovid19.setE1TieneTos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoTos)));
        cuestionarioCovid19.setE1TieneDificultadRespirar(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoDificultadRespirar)));
        cuestionarioCovid19.setE1TieneDolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoDolorPecho)));
        cuestionarioCovid19.setE1TienePalpitaciones(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoPalpitaciones)));
        cuestionarioCovid19.setE1TieneDolorArticulaciones(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoDolorArticulaciones)));
        cuestionarioCovid19.setE1TieneParalisis(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoParalisis)));
        cuestionarioCovid19.setE1TieneMareos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoMareos)));
        cuestionarioCovid19.setE1TienePensamientoNublado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoPensamientoNublado)));
        cuestionarioCovid19.setE1TieneProblemasDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoProblemasDormir)));
        cuestionarioCovid19.setE1TieneDepresion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoDepresion)));
        cuestionarioCovid19.setE1TieneOtrosSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TenidoOtrosSintomas)));
        cuestionarioCovid19.setE1cualesSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1CualesSintomas)));
        cuestionarioCovid19.setE1SabeTiempoRecuperacion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SabeTiempoRecuperacion)));
        cuestionarioCovid19.setE1TiempoRecuperacion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TiempoRecuperacion)));
        cuestionarioCovid19.setE1TiempoRecuperacionEn(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TiempoRecuperacionEn)));
        cuestionarioCovid19.setE1SeveridadEnfermedad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SeveridadEnfermedad)));
        cuestionarioCovid19.setE1TomoMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TomoMedicamento)));
        cuestionarioCovid19.setE1QueMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1QueMedicamento)));
        cuestionarioCovid19.setE1OtroMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1OtroMedicamento)));
        cuestionarioCovid19.setE1OxigenoDomicilio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1OxigenoDomicilio)));
        cuestionarioCovid19.setE1TiempoOxigenoDom(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TiempoOxigenoDom)));

        cuestionarioCovid19.setE2SabeFIS(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SabeFIS)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2FIS))>0) cuestionarioCovid19.setE2Fis(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2FIS))));
        cuestionarioCovid19.setE2MesInicioSintoma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2MesInicioSintoma)));
        cuestionarioCovid19.setE2AnioInicioSintoma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2AnioInicioSintoma)));
        cuestionarioCovid19.setE2ConoceLugarExposicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2ConoceLugarExposicion)));
        cuestionarioCovid19.setE2LugarExposicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2LugarExposicion)));
        cuestionarioCovid19.setE2BuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2BuscoAyuda)));
        cuestionarioCovid19.setE2DondeBuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DondeBuscoAyuda)));
        cuestionarioCovid19.setE2NombreCentroSalud(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2NombreCentroSalud)));
        cuestionarioCovid19.setE2NombreHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2NombreHospital)));
        cuestionarioCovid19.setE2RecibioSeguimiento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2RecibioSeguimiento)));
        cuestionarioCovid19.setE2TipoSeguimiento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TipoSeguimiento)));
        cuestionarioCovid19.setE2TmpDespuesBuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TmpDespuesBuscoAyuda)));
        cuestionarioCovid19.setE2UnaNocheHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2UnaNocheHospital)));
        cuestionarioCovid19.setE2QueHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2QueHospital)));
        cuestionarioCovid19.setE2SabeCuantasNoches(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SabeCuantasNoches)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2CuantasNochesHosp))>0) cuestionarioCovid19.setE2CuantasNochesHosp(cursor.getInt(cursor.getColumnIndex(Covid19DBConstants.e2CuantasNochesHosp)));
        cuestionarioCovid19.setE2SabeFechaAdmision(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SabeFechaAdmision)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2FechaAdmisionHosp))>0) cuestionarioCovid19.setE2FechaAdmisionHosp(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2FechaAdmisionHosp))));
        cuestionarioCovid19.setE2SabeFechaAlta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SabeFechaAlta)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2FechaAltaHosp))>0) cuestionarioCovid19.setE2FechaAltaHosp(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2FechaAltaHosp))));
        cuestionarioCovid19.setE2UtilizoOxigeno(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2UtilizoOxigeno)));
        cuestionarioCovid19.setE2EstuvoUCI(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2EstuvoUCI)));
        cuestionarioCovid19.setE2FueIntubado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2FueIntubado)));
        cuestionarioCovid19.setE2RecuperadoCovid19(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2RecuperadoCovid19)));
        cuestionarioCovid19.setE2TieneFebricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoFebricula)));
        cuestionarioCovid19.setE2TieneCansancio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoCansancio)));
        cuestionarioCovid19.setE2TieneDolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoDolorCabeza)));
        cuestionarioCovid19.setE2TienePerdidaOlfato(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoPerdidaOlfato)));
        cuestionarioCovid19.setE2TienePerdidaGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoPerdidaGusto)));
        cuestionarioCovid19.setE2TieneTos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoTos)));
        cuestionarioCovid19.setE2TieneDificultadRespirar(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoDificultadRespirar)));
        cuestionarioCovid19.setE2TieneDolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoDolorPecho)));
        cuestionarioCovid19.setE2TienePalpitaciones(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoPalpitaciones)));
        cuestionarioCovid19.setE2TieneDolorArticulaciones(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoDolorArticulaciones)));
        cuestionarioCovid19.setE2TieneParalisis(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoParalisis)));
        cuestionarioCovid19.setE2TieneMareos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoMareos)));
        cuestionarioCovid19.setE2TienePensamientoNublado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoPensamientoNublado)));
        cuestionarioCovid19.setE2TieneProblemasDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoProblemasDormir)));
        cuestionarioCovid19.setE2TieneDepresion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoDepresion)));
        cuestionarioCovid19.setE2TieneOtrosSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TenidoOtrosSintomas)));
        cuestionarioCovid19.setE2cualesSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2CualesSintomas)));
        cuestionarioCovid19.setE2SabeTiempoRecuperacion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SabeTiempoRecuperacion)));
        cuestionarioCovid19.setE2TiempoRecuperacion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TiempoRecuperacion)));
        cuestionarioCovid19.setE2TiempoRecuperacionEn(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TiempoRecuperacionEn)));
        cuestionarioCovid19.setE2SeveridadEnfermedad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SeveridadEnfermedad)));
        cuestionarioCovid19.setE2TomoMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TomoMedicamento)));
        cuestionarioCovid19.setE2QueMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2QueMedicamento)));
        cuestionarioCovid19.setE2OtroMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2OtroMedicamento)));
        cuestionarioCovid19.setE2OxigenoDomicilio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2OxigenoDomicilio)));
        cuestionarioCovid19.setE2TiempoOxigenoDom(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TiempoOxigenoDom)));


        cuestionarioCovid19.setE3SabeFIS(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SabeFIS)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3FIS))>0) cuestionarioCovid19.setE3Fis(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3FIS))));
        cuestionarioCovid19.setE3MesInicioSintoma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3MesInicioSintoma)));
        cuestionarioCovid19.setE3AnioInicioSintoma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3AnioInicioSintoma)));
        cuestionarioCovid19.setE3ConoceLugarExposicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3ConoceLugarExposicion)));
        cuestionarioCovid19.setE3LugarExposicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3LugarExposicion)));
        cuestionarioCovid19.setE3BuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3BuscoAyuda)));
        cuestionarioCovid19.setE3DondeBuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DondeBuscoAyuda)));
        cuestionarioCovid19.setE3NombreCentroSalud(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3NombreCentroSalud)));
        cuestionarioCovid19.setE3NombreHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3NombreHospital)));
        cuestionarioCovid19.setE3RecibioSeguimiento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3RecibioSeguimiento)));
        cuestionarioCovid19.setE3TipoSeguimiento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TipoSeguimiento)));
        cuestionarioCovid19.setE3TmpDespuesBuscoAyuda(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TmpDespuesBuscoAyuda)));
        cuestionarioCovid19.setE3UnaNocheHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3UnaNocheHospital)));
        cuestionarioCovid19.setE3QueHospital(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3QueHospital)));
        cuestionarioCovid19.setE3SabeCuantasNoches(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SabeCuantasNoches)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3CuantasNochesHosp))>0) cuestionarioCovid19.setE3CuantasNochesHosp(cursor.getInt(cursor.getColumnIndex(Covid19DBConstants.e3CuantasNochesHosp)));
        cuestionarioCovid19.setE3SabeFechaAdmision(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SabeFechaAdmision)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3FechaAdmisionHosp))>0) cuestionarioCovid19.setE3FechaAdmisionHosp(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3FechaAdmisionHosp))));
        cuestionarioCovid19.setE3SabeFechaAlta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SabeFechaAlta)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3FechaAltaHosp))>0) cuestionarioCovid19.setE3FechaAltaHosp(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3FechaAltaHosp))));
        cuestionarioCovid19.setE3UtilizoOxigeno(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3UtilizoOxigeno)));
        cuestionarioCovid19.setE3EstuvoUCI(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3EstuvoUCI)));
        cuestionarioCovid19.setE3FueIntubado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3FueIntubado)));
        cuestionarioCovid19.setE3RecuperadoCovid19(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3RecuperadoCovid19)));
        cuestionarioCovid19.setE3TieneFebricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoFebricula)));
        cuestionarioCovid19.setE3TieneCansancio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoCansancio)));
        cuestionarioCovid19.setE3TieneDolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoDolorCabeza)));
        cuestionarioCovid19.setE3TienePerdidaOlfato(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoPerdidaOlfato)));
        cuestionarioCovid19.setE3TienePerdidaGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoPerdidaGusto)));
        cuestionarioCovid19.setE3TieneTos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoTos)));
        cuestionarioCovid19.setE3TieneDificultadRespirar(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoDificultadRespirar)));
        cuestionarioCovid19.setE3TieneDolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoDolorPecho)));
        cuestionarioCovid19.setE3TienePalpitaciones(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoPalpitaciones)));
        cuestionarioCovid19.setE3TieneDolorArticulaciones(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoDolorArticulaciones)));
        cuestionarioCovid19.setE3TieneParalisis(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoParalisis)));
        cuestionarioCovid19.setE3TieneMareos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoMareos)));
        cuestionarioCovid19.setE3TienePensamientoNublado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoPensamientoNublado)));
        cuestionarioCovid19.setE3TieneProblemasDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoProblemasDormir)));
        cuestionarioCovid19.setE3TieneDepresion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoDepresion)));
        cuestionarioCovid19.setE3TieneOtrosSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TenidoOtrosSintomas)));
        cuestionarioCovid19.setE3cualesSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3CualesSintomas)));
        cuestionarioCovid19.setE3SabeTiempoRecuperacion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SabeTiempoRecuperacion)));
        cuestionarioCovid19.setE3TiempoRecuperacion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TiempoRecuperacion)));
        cuestionarioCovid19.setE3TiempoRecuperacionEn(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TiempoRecuperacionEn)));
        cuestionarioCovid19.setE3SeveridadEnfermedad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SeveridadEnfermedad)));
        cuestionarioCovid19.setE3TomoMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TomoMedicamento)));
        cuestionarioCovid19.setE3QueMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3QueMedicamento)));
        cuestionarioCovid19.setE3OtroMedicamento(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3OtroMedicamento)));
        cuestionarioCovid19.setE3OxigenoDomicilio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3OxigenoDomicilio)));
        cuestionarioCovid19.setE3TiempoOxigenoDom(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TiempoOxigenoDom)));

        cuestionarioCovid19.setPadeceEnfisema(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceEnfisema)));
        cuestionarioCovid19.setPadeceAsma(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceAsma)));
        cuestionarioCovid19.setPadeceDiabetes(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceDiabetes)));
        cuestionarioCovid19.setPadeceEnfCoronaria(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceEnfCoronaria)));
        cuestionarioCovid19.setPadecePresionAlta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padecePresionAlta)));
        cuestionarioCovid19.setPadeceEnfHigado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceEnfHigado)));
        cuestionarioCovid19.setPadeceEnfRenal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceEnfRenal)));
        cuestionarioCovid19.setPadeceInfartoDerrameCer(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceInfartoDerrameCer)));
        cuestionarioCovid19.setPadeceCancer(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceCancer)));
        cuestionarioCovid19.setPadeceCondicionInmuno(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceCondicionInmuno)));
        cuestionarioCovid19.setPadeceEnfAutoinmune(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceEnfAutoinmune)));
        cuestionarioCovid19.setPadeceDiscapacidadFis(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceDiscapacidadFis)));
        cuestionarioCovid19.setPadeceCondPsicPsiq(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceCondPsicPsiq)));
        cuestionarioCovid19.setPadeceOtraCondicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.padeceOtraCondicion)));
        cuestionarioCovid19.setQueOtraCondicion(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.queOtraCondicion)));
        cuestionarioCovid19.setFumado(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.fumado)));
        cuestionarioCovid19.setFumadoCienCigarrillos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.fumadoCienCigarrillos)));

        cuestionarioCovid19.setE1FumadoPrevioEnfermedad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1FumadoPrevioEnfermedad)));
        cuestionarioCovid19.setE1FumaActualmente(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1FumaActualmente)));
        //MA2021
        cuestionarioCovid19.setE1Embarazada(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Embarazada)));
        cuestionarioCovid19.setE1RecuerdaSemanasEmb(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1RecuerdaSemanasEmb)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e1SemanasEmbarazo))>0) cuestionarioCovid19.setE1SemanasEmbarazo(cursor.getInt(cursor.getColumnIndex(Covid19DBConstants.e1SemanasEmbarazo)));
        cuestionarioCovid19.setE1FinalEmbarazo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1FinalEmbarazo)));
        cuestionarioCovid19.setE1OtroFinalEmbarazo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1OtroFinalEmbarazo)));
        cuestionarioCovid19.setE1DabaPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DabaPecho)));

        cuestionarioCovid19.setE2FumadoPrevioEnfermedad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2FumadoPrevioEnfermedad)));
        cuestionarioCovid19.setE2FumaActualmente(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2FumaActualmente)));
        cuestionarioCovid19.setE2Embarazada(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Embarazada)));
        cuestionarioCovid19.setE2RecuerdaSemanasEmb(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2RecuerdaSemanasEmb)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e2SemanasEmbarazo))>0) cuestionarioCovid19.setE2SemanasEmbarazo(cursor.getInt(cursor.getColumnIndex(Covid19DBConstants.e2SemanasEmbarazo)));
        cuestionarioCovid19.setE2FinalEmbarazo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2FinalEmbarazo)));
        cuestionarioCovid19.setE2OtroFinalEmbarazo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2OtroFinalEmbarazo)));
        cuestionarioCovid19.setE2DabaPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DabaPecho)));

        cuestionarioCovid19.setE3FumadoPrevioEnfermedad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3FumadoPrevioEnfermedad)));
        cuestionarioCovid19.setE3FumaActualmente(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3FumaActualmente)));
        //MA2021
        cuestionarioCovid19.setE3Embarazada(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Embarazada)));
        cuestionarioCovid19.setE3RecuerdaSemanasEmb(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3RecuerdaSemanasEmb)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.e3SemanasEmbarazo))>0) cuestionarioCovid19.setE3SemanasEmbarazo(cursor.getInt(cursor.getColumnIndex(Covid19DBConstants.e3SemanasEmbarazo)));
        cuestionarioCovid19.setE3FinalEmbarazo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3FinalEmbarazo)));
        cuestionarioCovid19.setE3OtroFinalEmbarazo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3OtroFinalEmbarazo)));
        cuestionarioCovid19.setE3DabaPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DabaPecho)));

        cuestionarioCovid19.setTrabajadorSalud(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.trabajadorSalud)));
        cuestionarioCovid19.setPeriodoSintomas(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.periodoSintomas)));
        //Muestreo Familia Nov 2021
        cuestionarioCovid19.setEnfermoCovid19(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.enfermoCovid19)));
        cuestionarioCovid19.setCuantasVecesEnfermo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.cuantasVecesEnfermo)));
        cuestionarioCovid19.setSabeEvento1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.sabeEvento1)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.evento1))>0) cuestionarioCovid19.setEvento1(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.evento1))));
        cuestionarioCovid19.setAnioEvento1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.anioEvento1)));
        cuestionarioCovid19.setMesEvento1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.mesEvento1)));
        cuestionarioCovid19.setSabeEvento2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.sabeEvento2)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.evento2))>0) cuestionarioCovid19.setEvento2(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.evento2))));
        cuestionarioCovid19.setAnioEvento2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.anioEvento2)));
        cuestionarioCovid19.setMesEvento2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.mesEvento2)));
        cuestionarioCovid19.setSabeEvento3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.sabeEvento3)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.evento3))>0) cuestionarioCovid19.setEvento3(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.evento3))));
        cuestionarioCovid19.setAnioEvento3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.anioEvento3)));
        cuestionarioCovid19.setMesEvento3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.mesEvento3)));
        cuestionarioCovid19.setE1Febricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Febricula)));
        cuestionarioCovid19.setE1Fiebre(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Fiebre)));
        cuestionarioCovid19.setE1Escalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Escalofrio)));
        cuestionarioCovid19.setE1TemblorEscalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1TemblorEscalofrio)));
        cuestionarioCovid19.setE1DolorMuscular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DolorMuscular)));
        cuestionarioCovid19.setE1DolorArticular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DolorArticular)));
        cuestionarioCovid19.setE1SecresionNasal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1SecresionNasal)));
        cuestionarioCovid19.setE1DolorGarganta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DolorGarganta)));
        cuestionarioCovid19.setE1Tos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Tos)));
        cuestionarioCovid19.setE1DificultadResp(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DificultadResp)));
        cuestionarioCovid19.setE1DolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DolorPecho)));
        cuestionarioCovid19.setE1NauseasVomito(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1NauseasVomito)));
        cuestionarioCovid19.setE1DolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DolorCabeza)));
        cuestionarioCovid19.setE1DolorAbdominal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DolorAbdominal)));
        cuestionarioCovid19.setE1Diarrea(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Diarrea)));
        cuestionarioCovid19.setE1DificultadDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1DificultadDormir)));
        cuestionarioCovid19.setE1Debilidad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Debilidad)));
        cuestionarioCovid19.setE1PerdidaOlfatoGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1PerdidaOlfatoGusto)));
        cuestionarioCovid19.setE1Mareo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Mareo)));
        cuestionarioCovid19.setE1Sarpullido(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Sarpullido)));
        cuestionarioCovid19.setE1Desmayo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1Desmayo)));
        cuestionarioCovid19.setE1QuedoCama(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e1QuedoCama)));
        cuestionarioCovid19.setE2Febricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Febricula)));
        cuestionarioCovid19.setE2Fiebre(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Fiebre)));
        cuestionarioCovid19.setE2Escalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Escalofrio)));
        cuestionarioCovid19.setE2TemblorEscalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2TemblorEscalofrio)));
        cuestionarioCovid19.setE2DolorMuscular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DolorMuscular)));
        cuestionarioCovid19.setE2DolorArticular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DolorArticular)));
        cuestionarioCovid19.setE2SecresionNasal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2SecresionNasal)));
        cuestionarioCovid19.setE2DolorGarganta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DolorGarganta)));
        cuestionarioCovid19.setE2Tos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Tos)));
        cuestionarioCovid19.setE2DificultadResp(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DificultadResp)));
        cuestionarioCovid19.setE2DolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DolorPecho)));
        cuestionarioCovid19.setE2NauseasVomito(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2NauseasVomito)));
        cuestionarioCovid19.setE2DolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DolorCabeza)));
        cuestionarioCovid19.setE2DolorAbdominal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DolorAbdominal)));
        cuestionarioCovid19.setE2Diarrea(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Diarrea)));
        cuestionarioCovid19.setE2DificultadDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2DificultadDormir)));
        cuestionarioCovid19.setE2Debilidad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Debilidad)));
        cuestionarioCovid19.setE2PerdidaOlfatoGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2PerdidaOlfatoGusto)));
        cuestionarioCovid19.setE2Mareo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Mareo)));
        cuestionarioCovid19.setE2Sarpullido(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Sarpullido)));
        cuestionarioCovid19.setE2Desmayo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2Desmayo)));
        cuestionarioCovid19.setE2QuedoCama(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e2QuedoCama)));
        cuestionarioCovid19.setE3Febricula(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Febricula)));
        cuestionarioCovid19.setE3Fiebre(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Fiebre)));
        cuestionarioCovid19.setE3Escalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Escalofrio)));
        cuestionarioCovid19.setE3TemblorEscalofrio(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3TemblorEscalofrio)));
        cuestionarioCovid19.setE3DolorMuscular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DolorMuscular)));
        cuestionarioCovid19.setE3DolorArticular(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DolorArticular)));
        cuestionarioCovid19.setE3SecresionNasal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3SecresionNasal)));
        cuestionarioCovid19.setE3DolorGarganta(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DolorGarganta)));
        cuestionarioCovid19.setE3Tos(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Tos)));
        cuestionarioCovid19.setE3DificultadResp(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DificultadResp)));
        cuestionarioCovid19.setE3DolorPecho(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DolorPecho)));
        cuestionarioCovid19.setE3NauseasVomito(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3NauseasVomito)));
        cuestionarioCovid19.setE3DolorCabeza(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DolorCabeza)));
        cuestionarioCovid19.setE3DolorAbdominal(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DolorAbdominal)));
        cuestionarioCovid19.setE3Diarrea(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Diarrea)));
        cuestionarioCovid19.setE3DificultadDormir(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3DificultadDormir)));
        cuestionarioCovid19.setE3Debilidad(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Debilidad)));
        cuestionarioCovid19.setE3PerdidaOlfatoGusto(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3PerdidaOlfatoGusto)));
        cuestionarioCovid19.setE3Mareo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Mareo)));
        cuestionarioCovid19.setE3Sarpullido(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Sarpullido)));
        cuestionarioCovid19.setE3Desmayo(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3Desmayo)));
        cuestionarioCovid19.setE3QuedoCama(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.e3QuedoCama)));
        cuestionarioCovid19.setVacunadoCovid19(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.vacunadoCovid19)));
        cuestionarioCovid19.setMuestraTarjetaVac(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.muestraTarjetaVac)));
        cuestionarioCovid19.setSabeNombreVacuna(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.sabeNombreVacuna)));
        cuestionarioCovid19.setNombreVacuna(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nombreVacuna)));
        cuestionarioCovid19.setAnioVacuna(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.anioVacuna)));
        cuestionarioCovid19.setMesVacuna(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.mesVacuna)));
        cuestionarioCovid19.setCuantasDosis(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.cuantasDosis)));
        cuestionarioCovid19.setNombreDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nombreDosis1)));
        cuestionarioCovid19.setOtraVacunaDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.otraVacunaDosis1)));
        cuestionarioCovid19.setLoteDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.loteDosis1)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaDosis1))>0) cuestionarioCovid19.setFechaDosis1(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaDosis1))));
        cuestionarioCovid19.setNombreDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nombreDosis2)));
        cuestionarioCovid19.setOtraVacunaDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.otraVacunaDosis2)));
        cuestionarioCovid19.setLoteDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.loteDosis2)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaDosis2))>0) cuestionarioCovid19.setFechaDosis2(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaDosis2))));
        cuestionarioCovid19.setNombreDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nombreDosis3)));
        cuestionarioCovid19.setOtraVacunaDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.otraVacunaDosis3)));
        cuestionarioCovid19.setLoteDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.loteDosis3)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaDosis3))>0) cuestionarioCovid19.setFechaDosis3(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaDosis3))));

        cuestionarioCovid19.setPresentoSintomasDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.presentoSintomasDosis1)));
        cuestionarioCovid19.setDolorSitioDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorSitioDosis1)));
        cuestionarioCovid19.setFiebreDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.fiebreDosis1)));
        cuestionarioCovid19.setCansancioDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.cansancioDosis1)));
        cuestionarioCovid19.setDolorCabezaDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorCabezaDosis1)));
        cuestionarioCovid19.setDiarreaDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.diarreaDosis1)));
        cuestionarioCovid19.setVomitoDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.vomitoDosis1)));
        cuestionarioCovid19.setDolorMuscularDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorMuscularDosis1)));
        cuestionarioCovid19.setEscalofriosDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.escalofriosDosis1)));
        cuestionarioCovid19.setReaccionAlergicaDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.reaccionAlergicaDosis1)));
        cuestionarioCovid19.setInfeccionSitioDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.infeccionSitioDosis1)));
        cuestionarioCovid19.setNauseasDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nauseasDosis1)));
        cuestionarioCovid19.setBultosDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.bultosDosis1)));
        cuestionarioCovid19.setOtrosDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.otrosDosis1)));
        cuestionarioCovid19.setDesOtrosDosis1(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.desOtrosDosis1)));

        cuestionarioCovid19.setPresentoSintomasDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.presentoSintomasDosis2)));
        cuestionarioCovid19.setDolorSitioDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorSitioDosis2)));
        cuestionarioCovid19.setFiebreDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.fiebreDosis2)));
        cuestionarioCovid19.setCansancioDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.cansancioDosis2)));
        cuestionarioCovid19.setDolorCabezaDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorCabezaDosis2)));
        cuestionarioCovid19.setDiarreaDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.diarreaDosis2)));
        cuestionarioCovid19.setVomitoDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.vomitoDosis2)));
        cuestionarioCovid19.setDolorMuscularDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorMuscularDosis2)));
        cuestionarioCovid19.setEscalofriosDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.escalofriosDosis2)));
        cuestionarioCovid19.setReaccionAlergicaDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.reaccionAlergicaDosis2)));
        cuestionarioCovid19.setInfeccionSitioDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.infeccionSitioDosis2)));
        cuestionarioCovid19.setNauseasDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nauseasDosis2)));
        cuestionarioCovid19.setBultosDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.bultosDosis2)));
        cuestionarioCovid19.setOtrosDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.otrosDosis2)));
        cuestionarioCovid19.setDesOtrosDosis2(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.desOtrosDosis2)));

        cuestionarioCovid19.setPresentoSintomasDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.presentoSintomasDosis3)));
        cuestionarioCovid19.setDolorSitioDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorSitioDosis3)));
        cuestionarioCovid19.setFiebreDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.fiebreDosis3)));
        cuestionarioCovid19.setCansancioDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.cansancioDosis3)));
        cuestionarioCovid19.setDolorCabezaDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorCabezaDosis3)));
        cuestionarioCovid19.setDiarreaDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.diarreaDosis3)));
        cuestionarioCovid19.setVomitoDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.vomitoDosis3)));
        cuestionarioCovid19.setDolorMuscularDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.dolorMuscularDosis3)));
        cuestionarioCovid19.setEscalofriosDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.escalofriosDosis3)));
        cuestionarioCovid19.setReaccionAlergicaDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.reaccionAlergicaDosis3)));
        cuestionarioCovid19.setInfeccionSitioDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.infeccionSitioDosis3)));
        cuestionarioCovid19.setNauseasDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.nauseasDosis3)));
        cuestionarioCovid19.setBultosDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.bultosDosis3)));
        cuestionarioCovid19.setOtrosDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.otrosDosis3)));
        cuestionarioCovid19.setDesOtrosDosis3(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.desOtrosDosis3)));

        cuestionarioCovid19.setCovid19PosteriorVacuna(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.covid19PosteriorVacuna)));
        cuestionarioCovid19.setSabeFechaEnfPostVac(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.sabeFechaEnfPostVac)));
        if(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaEnfPostVac))>0) cuestionarioCovid19.setFechaEnfPostVac(new Date(cursor.getLong(cursor.getColumnIndex(Covid19DBConstants.fechaEnfPostVac))));
        cuestionarioCovid19.setAnioEnfPostVac(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.anioEnfPostVac)));
        cuestionarioCovid19.setMesEnfPostVac(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.mesEnfPostVac)));
        cuestionarioCovid19.setFechaEventoEnfermoPostVac(cursor.getString(cursor.getColumnIndex(Covid19DBConstants.fechaEventoEnfermoPostVac)));

        if(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))>0) cuestionarioCovid19.setRecordDate(new Date(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))));
        cuestionarioCovid19.setRecordUser(cursor.getString(cursor.getColumnIndex(MainDBConstants.recordUser)));
        cuestionarioCovid19.setPasive(cursor.getString(cursor.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        cuestionarioCovid19.setEstado(cursor.getString(cursor.getColumnIndex(MainDBConstants.estado)).charAt(0));
        cuestionarioCovid19.setDeviceid(cursor.getString(cursor.getColumnIndex(MainDBConstants.deviceId)));
        return cuestionarioCovid19;
    }

}
